[package]
name = "kif-crdgen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
description.workspace = true

[dependencies]
kif-api = { path = "../kif-api" }

anyhow.workspace = true
kube.workspace = true
serde_yaml.workspace = true
