apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kif.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kif.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
subjects:
  - kind: ServiceAccount
    name: {{ .Values.issuer.serviceAccount.name | default (printf "%s-issuer" (include "kif.fullname" .)) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kif.fullname" . }}-issuer
  apiGroup: rbac.authorization.k8s.io
