apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kif.fullname" . }}-federation
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: federation
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["64f.dev"]
    resources: ["resolvedcloudrolebindings"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kif.fullname" . }}-federation
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: federation
subjects:
  - kind: ServiceAccount
    name: {{ .Values.federation.serviceAccount.name | default (printf "%s-federation" (include "kif.fullname" .)) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kif.fullname" . }}-federation
  apiGroup: rbac.authorization.k8s.io
