apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.federation.serviceAccount.name | default (printf "%s-federation" (include "kif.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: federation
