apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kif.fullname" . }}-webhook
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  {{- if .Values.webhook.tls.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-webhook" .Release.Namespace (include "kif.fullname" .) }}
  {{- end }}
webhooks:
  - name: kif-webhook.64f.dev
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.config.admissionFailureMode }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: {{ include "kif.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate
        port: {{ .Values.webhook.service.port }}
      {{- if not .Values.webhook.tls.certManager.enabled }}
      caBundle: {{ .Values.webhook.tls.caBundle | quote }}
      {{- end }}
