apiVersion: v1
kind: Service
metadata:
  name: kif-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  selector:
    {{- include "kif.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  ports:
    - name: https
      port: {{ .Values.webhook.service.port }}
      targetPort: https
      protocol: TCP
