{{- if .Values.webhook.tls.certManager.enabled }}
{{- $tlsSecret := .Values.webhook.tls.secretName | default (printf "%s-webhook-tls" (include "kif.fullname" .)) -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kif.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  secretName: {{ $tlsSecret }}
  dnsNames:
    - {{ include "kif.fullname" . }}-webhook
    - {{ include "kif.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "kif.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "kif.fullname" . }}-webhook-selfsigned
    kind: Issuer
{{- end }}
