{{- if .Values.webhook.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kif-webhook-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kif.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  selfSigned: {}
{{- end }}
